config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about", to: "pages#about"
  resources :articles
  get "signup", to: "users#new"
  resources :users, except: [:new]
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord 
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 450 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord

  belongs_to :article 
  belongs_to :category

end

app/models/category.rb
class Category < ApplicationRecord 
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 25 }
end 

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 105 }, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
      
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # before actions allways in order ! 
  before_action :set_article, only: [ :show, :edit, :update, :destroy ]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
  end

  def index 
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new 
    @article = Article.new
  end 

  def edit
  end

  def create 
    @article = Article.new(article_params) #Security to admit creation, or update 
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was created succesfully !"
      redirect_to @article
    else
      render "new"
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article was succesfully updated !"
      redirect_to @article
    else
      render "edit"
    end
  end

  def destroy
    @article.destroy
    flash[:warning] = "The article has been deleted"
    redirect_to user_path(@article.user)
  end

  private

  def require_same_user
    if current_user!= @article.user and !current_user.admin?
      flash[:danger] = "You can only edit or delete your own articles"
      redirect_to root_path
    end
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def new
    @category = Category.new
  end

  def show 
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end 

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end 

  def create
    @category = Category.new(category_params)
    if @category.save 
      flash[:success] = "Category was created successfully"
      redirect_to categories_path
    else
      render "new"
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category name was successfully updated"
      redirect_to category_path(@category)
    else
      render "edit"
    end
  end

  def destroy
  end

  private 

  def require_admin
    if !logged_in? || (logged_in? and !current_user.admin?)
      flash[:danger] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home 
    #redirect_to articles_path if logged_in?
  end

  def about
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
end

def create
  user = User.find_by(email: params[:session][:email].downcase)
  if user && user.authenticate(params[:session][:password])
    session[:user_id] = user.id
    flash[:success] = "Logged in successfully!"
    redirect_to user
  else
    flash.now[:danger] = "There was something wrong with your login details"
    render "new"
  end
  #flash.now is used when we dont redirect to another page, is shows up "now"
  # params[:session][:email]
  # params[:session][:password]
end

def destroy
  session[:user_id] = nil
  flash[:success] = "Logged out"
  redirect_to root_path
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def show 
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @user = User.new
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def edit 
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your profile was successfully updated!"
      redirect_to @user
    else
      render "edit"
    end
  end
  
  def create 
    @user = User.new(user_params) #Security to admit creation, or update
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the Alpha Blog #{@user.username}, you have successfully signed up!"
      redirect_to user_path(@user)
    else
      render "new"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles have been deleted"
    redirect_to users_path
  end
     

  private

  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:warning] = "You can only edit your own account"
      redirect_to root_path
    end
  end

  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "Only admin users can perform this action"
      redirect_to user_path
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "profile-img mt-4 rounded shadow mx-auto d-block")
  end

end

app/helpers/pages_helper.rb
module PagesHelper


end

app/views/articles/_articles.html.erb
<div class="container">
  <% obj.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <% if article.user %>
              Created by <%= link_to article.user.username, user_path(article.user) %> 
            <% end %>
          </div>
          <div class="card-body">
            <h4 class="card-title"><%= link_to article.title, article_path(article.id), id: "article-list-title", class: "text-decoration-none text-capitalize" %></h4>
            <hr>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <% if article.categories.any? %>
              <p class="mt-3 mb-3">Categories: <%= render article.categories %></p>
            <% end %>
            <%= link_to "View", article_path(article.id), class: "btn btn-sm btn-outline-dark" %>
            <% if logged_in? && (current_user == article.user || current_user.admin?) %>
              <%= link_to "Edit", edit_article_path(article.id), class: "btn btn-sm btn-outline-dark" %>
              <%= link_to "Delete", article_path(article.id), method: :delete, class: "btn btn-sm btn-outline-danger", data: {confirm: "Do you really want to delete this article ?"} %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago, Edited <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render "shared/errors", obj: @article %>
      <%= form_with(model: @article, id: "form", class: "shadow p-3 mb-3 bg-warning rounded text-light", local: true) do |f| %>
        <div class="form-group row">  
          <%= f.label :title, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-laber" %>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Content" %>
          </div> 
        </div>
       
        <div class="form-group row form-check form-check-inline">
          <%= f.label :categories, class: "col-2 col-form-laber" %>
          <div class="col-10">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <% cb.label(class: "form-check-label mb-2") {cb.check_box(class: "form-check-input ml-4") + cb.text} %>
            <% end %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row justify-content-center">
    <%= link_to "[ Cancel ]", articles_path, class: " text-info text-decoration-none" %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit Article</h1>

<%= render "form" %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">List of articles</h1>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render "articles", obj: @articles %>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Write a New Article</h1>

<%= render "form" %> 

app/views/articles/show.html.erb
<h2 class="text-center mt-4 text-capitalize"><%= @article.title %></h2>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          by <%= @article.user.username %>
          <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
        </div>
        <div class="card-body">
          <div class="card-text text-left"><%= simple_format(@article.description) %></div>
          <% if @article.categories.any? %>
            <p class="text-left pt-4">Categories: <%= render @article.categories %></p>
          <% end %>
          <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
            <%= link_to "Edit", edit_article_path(@article.id), class: "btn btn-sm btn-outline-dark" %>
            <%= link_to "Delete", article_path(@article.id), method: :delete, class: "btn btn-sm btn-outline-danger", data: {confirm: "Do you really want to delete this article ?"} %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(@article.created_at) %> ago, Edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
  <div class="row justify-content-md-center">
    <%= link_to "[ Return to articles ]", articles_path, class: "text-info text-decoration-none" %> 
  </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-secondary" %> &nbsp;

app/views/categories/_form.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render "shared/errors", obj: @category %>
      <%= form_with(model: @category, id: "form", class: "shadow p-3 mb-3 bg-warning rounded text-light", local: true) do |f| %>
        <div class="form-group row">  
          <%= f.label :name, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Category name" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row justify-content-center">
    <%= link_to "[ Cancel ]", root_path, class: " text-info text-decoration-none" %>
  </div>
</div>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Modify Category</h1>

<%= render "form" %> 

app/views/categories/index.html.erb
<h1 class="text-center mt-4 mb-3">Listing all categories</h1>

<div class="flickr_pagination">
  <%= will_paginate @categories, :container => false %>
</div>

<div class="container">
  <% @categories.each do |category| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <%= link_to category.name, category_path(category), class: "btn btn-lg btn-outline-dark" %> <br>
            <small><%= pluralize(category.articles.count, "articles") %></small>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(category.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>    
  <% end %>  
</div>

<div class="flickr_pagination">
  <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create New Category</h1>

<%= render "form" %> 

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>

<h4 class="text-muted text-center mt-4"><%= @category_articles.count %> articles associated with this category</h4>

<% if logged_in? and current_user.admin? %>
  <div class="row justify-content-md-center">
    <%= link_to "Edit category name", edit_category_path(@category), class: "badge badge-pill badge-secondary mr-3" %>
    <%= link_to "Delete Category", category_path(@category), method: :delete, data: {confirm: "Do you really want to delete this category?"}, class: "badge badge-pill badge-danger" %>
  </div>
<% end %>

<div class="flickr_pagination mt-4">
  <%= will_paginate @category_articles, :container => false %>
</div>

<%= render "articles/articles", obj: @category_articles %>

<div class="flickr_pagination">
  <%= will_paginate @category_articles, :container => false %>
</div>

app/views/layouts/_footer.html.erb
</div>
<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Made with love &copy; Copyright <%= link_to "Alpha Blog", "http://google.com", class: "text-white" %></small>
    </div>
  </footer>

app/views/layouts/_message.html.erb
<div class="container mt-4">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name %> alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= msg %>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Articles", articles_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Bloggers", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "All Categories", categories_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <% Category.all.each do |category| %>
            <%= link_to category.name, category_path(category), class: "dropdown-item" %>
          <% end %>
        </div>
      </li>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control ml-3 mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="navbar-btn btn btn-outline-danger my-2 my-sm-0" type="submit">Search</button>
      </form>
    </ul>
    <ul class="navbar-nav navbar-right">
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Your <%= "Admin" if current_user.admin? %> Profil
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Create New Article", new_article_path, class: "dropdown-item" %>
            <% if logged_in? and current_user.admin? %>
              <%= link_to "Create New Category", new_category_path, class: "dropdown-item" %>
            <% end %>
            <%= link_to "View your profil", user_path(current_user), class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Edit your profil", edit_user_path(current_user), class: "dropdown-item" %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to "Logout", logout_path, class: "nav-link", method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Signup", signup_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>          
  </div>
</nav>

<div id="page-content" class="pb-4"> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render "layouts/navigation" %>
    <%= render "layouts/message" %>  
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the About page of the Alpha-blog</h1>

<%= link_to "Articles", articles_path %> |
<%= link_to "Home Page", root_path %>

app/views/pages/home.html.erb
<!-- home page bootstrap jumbotron, -->
<div class="container mt-5" id="home-container">
  <div class="jumbotron text-center">
    <% if logged_in? %>
      <h1 class="display-4">Welcome <%= current_user.username %> </h1>
      <p class="lead">Start sharing your journey of learning to code.</p>
      <%= link_to "Publish a new article!", new_article_path, class: "btn btn-danger btn-lg" %>
    <% else %>
    <h1 class="display-4">Welcome to the Alpha Blog</h1>
    <p class="lead">Start sharing your journey of learning to code.</p>
    <p>Join to tell us your coding progress, read other blog articles from other people and interact with your friends from the Alpha Blog community.</p>
    <%= link_to "Sign Up!", signup_path, class: "btn btn-danger btn-lg" %>
    <% end %>
  </div>
</div> 

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dissmissable fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved:</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container mt-4">
<div class="row justify-content-center">
  <div class="col-10">
    <%= render "shared/errors", obj: @user %>
    <%= form_with(model: @user, id: "form", class: "shadow p-3 mb-3 bg-warning rounded text-light", local: true) do |f| %>
      <div class="form-group row">  
        <%= f.label :username, class: "col-2 col-form-label" %>
        <div class="col-10">
          <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :email, class: "col-2 col-form-laber" %>
        <div class="col-10">
          <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email" %>
        </div> 
      </div>

      <div class="form-group row">
        <%= f.label :password, class: "col-2 col-form-laber" %>
        <div class="col-10">
          <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Enter a password" %>
        </div> 
      </div>

      <div class="form-group row justify-content-center">
        <%= f.submit(@user.new_record? ? "Sign Up" : "Update Account", class: "btn btn-outline-light btn-lg") %>
      </div>
    <% end %>
  </div>
</div>
<div class="row justify-content-center">
  <%= link_to "[ Cancel ]", root_path, class: " text-info text-decoration-none" %>
</div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>

<%= render "form" %>

app/views/users/index.html.erb
<h1 class="text-center mt-4 mb-3">Alpha Bloggers</h1>

<div class="flickr_pagination">
  <%= will_paginate @users, :container => false %>
</div>

<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%= link_to user.username, user %> 
          </div>
          <div class="card-body">
            <h4 class="card-title">
              <%= link_to gravatar_for(user, size: 150), user %>
            </h4>
            <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
            <%= link_to "View Profile", user, class: "btn btn-sm btn-outline-dark" %>
            <% if logged_in? && current_user == user %>
              <%= link_to "Edit Profile", edit_user_path(user), class: "btn btn-sm btn-outline-dark" %>
            <% end %>
            <% if logged_in? and current_user.admin? %>
              <%= link_to "Delete User", user_path(user), class: "btn btn-sm btn-outline-danger", method: :delete, data: { confirm: "Are you sure you want to delete this user and all their articles?" } %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination">
  <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign Up for the Alpha Blog</h1>

<%= render "form" %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>

<%= gravatar_for @user, size: 200 %>

<div class="text-center mt-4">
  <% if logged_in? && current_user == @user %>
    <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-dark" %>
  <% end %>
  <% if logged_in? and current_user.admin? %>
    <%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-outline-dark" %>
    <%= link_to "Delete User", user_path(@user), class: "btn btn-outline-danger", method: :delete, data: { confirm: "Are you sure you want to delete this profile and all their articles?" } %>
  <% end %>
</div>

<h4 class="text-center mt-4">Articles</h4>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render "articles/articles", obj: @articles %>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>